[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, apikey, x-client-info"
    Content-Security-Policy = "default-src * 'unsafe-inline' 'unsafe-eval' data: blob:;"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
